name: Repo Dispatch

on:
  repository_dispatch:
    types: [docker-build]
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login
      if: false
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
      uses: docker/login-action@v2.0.0
      with:
        # Username used to log against the Docker registry
        username: frantzme
        # Password or personal access token used to log against the Docker registry
        password: ${{secrets.DOCKER_TOKEN}}
    
    - name: Make the mini files
      if: false
      run: make mini
    
    - name: Build the docker image
      if: false
      run: docker build . --file Dockerfile --tag frantzme/base_docker:latest
    
    - name: Docker Push
      if: false
      run: docker push frantzme/base_docker_builder

  dispatch:
    needs: build
    strategy:
      matrix:
        repo: ['franceme/rustdev_lite', 'franceme/pythondev_lite', 'franceme/pythondev_min', 'franceme/javadev_lite', 'franceme/writer_lite', 'franceme/dev_lite', 'franceme/ml_lite','franceme/pythontesting_lite','franceme/rustpy_lite','franceme/scalapy_lite', 'franceme/ballerina_lite']
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: docker-build
