name: Repo Dispatch

on:
  repository_dispatch:
    types: [docker-build]
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Make mini scripts
      run: make mini
    
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: frantzme
        password: ${{secrets.DOCKER_TOKEN}}
    
    - name: Build the docker image
      run: docker build . --file Dockerfile --tag frantzme/texbuilder:2020

    - name: Docker Push
      run: docker push frantzme/texbuilder:2020